{% set name = "libatomic_ops" %}
{% set version = "7.6.2" %}
{% set sha256 = "219724edad3d580d4d37b22e1d7cb52f0006d282d26a9b8681b560a625142ee6"%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ivmai/{{ name }}/releases/download/v{{ version }}/libatomic_ops-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain

test:
  commands:
    - test -e $PREFIX/include/atomic_ops.h
    - test -e $PREFIX/lib/libatomic_ops.a

about:
  home: https://github.com/ivmai/libatomic_ops
  license: Custom
  summary: Implementations for atomic memory update operations.

extra:
  recipe-maintainers:
    - stefan-balke
